######################################################

# Deterimining Gain or Loss of Functional Domains in Novel Protein Isoforms
# Author: Alyssa Klein
# Date: January 5, 2020
# Updated: February 12, 2020

#####################################################

# There are two main things occurring in this script, with the main goal being to identify the loss/gain of functional domains when going from
# the canonical protein to the novel isoform. The first step of the script takes in the domain information files that have been generated
# for both the canonical domains and the isoform domains through the use of Amazon Web Services (AWS). These files have been simplified from what was
# generated by AWS (which outputs a .html) file- see the README file for more information as to what information is need in each of these files.
# The next step is the generation of an individual file for each unique Seq_ID (i.e. UniProt ID) that contains the domain assignments for each, the evalues, 
# and match regions.  The final step of the script is the output of loss/gain of domains.  This is outputted as a text file with the name "domain_information_output.txt".

#####################################################
# Step One: Read in both csv files that contain the domain assignment information for the canonical sequence and the novel isoform sequences.

# Read in the csv file that contains the Superfamily domains assigned to the canonical sequences
# Note these are the domains identified through the use of AWS where the Superfamily cloude image is avaiable for use
domains_canonical <- read.csv("superfamily_domains_canonical_for_script.csv", header=TRUE, sep= ",")

# Read in the csv file that contains the Superfamily domains assigned to the isoform sequences
# Note these are the domains identified through the use of Amazon Web Services (AWS) where the Superfamily cloude image is avaiable for use
domains_isoform <- read.csv("superfamily_domains_isoform_for_script.csv", header=TRUE, sep=",")

#####################################################
# Step Two: Creation of a for loop to generate file for each unique Seq_ID.

# The following for loop generates an individual file for each protein which contains a table of their canonical domains and isoform domains.
# One can distinguish which domain is associated with each protein with "_canonical" or "_isoform" preceded by the name of the protein (this is the "Protein_name" column of the above domain file)

# set i equal to 1 to begin the for loop in the following lines
i <- 1
# place the canonical domain "Seq_ID"s into a list (these are equivalent to the UniProt IDs)
id_list <- as.list(domains_canonical$Seq_ID)
# extract only the unique "Seq_ID"s since each domain is listed as an individual entry (and therefore a Seq_ID could be listed more than once)
unique_ids_only <- unique(id_list)
# place the canonical domain "Protein_name"s into a list
protein_names_list <- as.list(domains_canonical$Protein_name)
# extract only the unique "Protein_name"s since each domain is listed as an individual entry (and therefore a Protein_name could be listed more than once)
unique_protein_names_only <- unique(protein_names_list)

# begin the for loop using the unique Seq_IDs (i.e. UniProt IDs)
for (protein in unique_ids_only) {
  
  # Note: all of the steps below are generating the information that will be included in each individual protein file:
  # domain assignments (SCOP_superfamily), evalues (E_value), and match regions (Match_region)
  
  # extract the domains from the canonical table for the given unique id 
  canonical_table <- domains_canonical$SCOP_superfamily[which(domains_canonical$Seq_ID == unique_ids_only[[i]])]
  # extract the domains from the isoform table for the given unique id
  isoform_table <- domains_isoform$SCOP_superfamily[which(domains_isoform$Seq_ID == unique_ids_only[[i]])]
  
  # extract the evalues from the canonical table for the given unique id 
  canonical_evalues <- domains_canonical$E_value[which(domains_canonical$Seq_ID == unique_ids_only[[i]])]
  # extract the evalues from the isoform table for the given unique id 
  isoform_evalues <- domains_isoform$E_value[which(domains_isoform$Seq_ID == unique_ids_only[[i]])]
  
  # extract the "Match_region" from the canonical table for the given unique id
  canonical_match_region <- domains_canonical$Match_region[which(domains_canonical$Seq_ID == unique_ids_only[[i]])]
  # extract the "Match_region" from the isoform table for the given unique id
  isoform_match_region <- domains_isoform$Match_region[which(domains_isoform$Seq_ID == unique_ids_only[[i]])]
  
  # convert the information for both sequence types into a dataframe
  # convert the canonical table information extracted into a dataframe 
  canonical_df <- data.frame("Protein_name" = paste0(domains_canonical$Protein_name[which(domains_canonical$Seq_ID == unique_ids_only[[i]])] , "_canonical"), 
                             "Domains" = canonical_table, "Match_region" = canonical_match_region, "E-value" = canonical_evalues )
  # convert the isoform table information extracted into a dataframe 
  isoform_df <- data.frame("Protein_name" = paste0(domains_isoform$Protein_name[which(domains_isoform$Seq_ID == unique_ids_only[[i]])] , "_isoform"), 
                           "Domains" = isoform_table, "Match_region" = isoform_match_region, "E-value" = isoform_evalues)
  
  # use the full_join() function to combine the information for both the canonical and isoform sequences into one table for each protein
  canonical_and_isoform_one_table <- full_join(canonical_df, isoform_df)
  
  # convert the table of information for both the canonica and the isoform into a dataframe
  canonical_and_isoform_one_table <- data.frame(canonical_and_isoform_one_table)
  
  # write the dataframe that has been created to a file
  # a file will be generated for each individual protein (i.e. each unique Protein_name)
  # the naming for each file will consist of the "Protein_name_Seq_id_domains_canonical_isoform_compared.csv"
  # example of a file name for a file generated: "AAMDC_Q9H7C9_domains_canonical_isoform_compared.csv"
  write.csv(canonical_and_isoform_one_table, file= paste0(unique_protein_names_only[[i]], "_", unique_ids_only[[i]], "_domains_canonical_isoform_compared.csv"), sep = ",", col.names = TRUE)
  
  # iterate i by one each time through the loop in order to generate the file of domain information for the next unique Seq_ID (i.e. UniProt ID)
  i <- i + 1
}

#####################################################
# Step Three: Output the loss/gain of domains as a text file with the name "domain_information_output.txt".

# use of the psate0() function to piece together each of the file names that were generated in Step Two
# store as domin_paste object- which will be used in the for loop below
domain_paste <- paste0(unique(domains_canonical$Protein_name), "_",unique(domains_canonical$Seq_ID), "_domains_canonical_isoform_compared.csv")

# check that the length of the domain_paste is the number of files that you previously generated
length(domain_paste)
# [1] 32

# create a data frame to store each unique Protein_name
# eventually this will be appended to tell the user if the canonical protein has domains assigned to it intially
df_canonical_initially <- data.frame("Protein_name"= unique(domains_canonical$Protein_name))

# set i equal to 1 to begin the for loop in the following lines
i <- 1

# for loop to identify loss/gain, or no change in domains for each file generated in the previous step 
# compare the domains between the canonical and the novel isoforms to look for loss/gain or domains
for (files in domain_paste){ 
  # print the file name so the user knows which file is currently being read in the loop
  print(files)
  # use of the cat function to append the filename to the output text file
  cat(domain_paste[[i]],file= "domain_information_output.txt",append=TRUE, sep = "\n")
  
  # read in the file currently being iterated over, and store its contents as test_for_gain_loss
  test_for_gain_loss <- read.csv(domain_paste[[i]], header=TRUE, sep= ",")

  # extract the domains for the canonical protein (everything where the Protein_name ends in "_canonical")
  canonical_domains <- test_for_gain_loss$Domains[which(test_for_gain_loss$Protein_name == levels(unique(test_for_gain_loss$Protein_name))[1])]
  # extract the domains for the isoform (everything where the Protein_name ends in "_isoform")
  isoform_domains <- test_for_gain_loss$Domains[which(test_for_gain_loss$Protein_name == levels(unique(test_for_gain_loss$Protein_name))[2])]

  # place the canonical domains extracted into a list
  canonical_domain_list <- as.list(canonical_domains)
  # place the isoform domains extracted into a list
  isoform_domain_list <- as.list(isoform_domains)
  
  # check for gain of domains using the %in% function
  # checking to see if all elements of the isoform domain list are in the canonical domain list
  gain_of_domains <- isoform_domain_list %in% canonical_domain_list
  # check for loss of domains using the %in% function
  # checking to see if all elements of the canonical domain list are in the isoform domain list
  loss_of_domains <- canonical_domain_list %in% isoform_domain_list
  
  # generate individual tables for both the canonical domains and the isoform domains
  # generate table for the canonical domains
  table_canonical <- table(canonical_domains)
  # make the table for the canonical domains into a dataframe- this lists the number of each domain as a frequency
  df_canonical <- data.frame(table_canonical)
  # generate table for the isoform domains
  table_isoform <- table(isoform_domains)
  # make the table for the canonical domains into a dataframe- this lists the number of each domain as a frequency
  df_isoform <- data.frame(table_isoform)
  
  # check to see if there were any domains for the canonical protein identified initially
  # value of "no" placed in the table if no domains were initially identified
  # value of "yes" placed in the table if there were domains initially identified
  if(identical(toString(canonical_domains), "NA") == FALSE){
    # let the user know there were domains identified in the canonical sequence initially
    canonical_domains_init <- "yes"
    # add column to df_canonical_initially that will have a value of "yes" for that specific Protein_name
    df_canonical_initially$Canonical_Domains_Initially[[i]] <- canonical_domains_init
    #print(df$Canonical_Domains_Initially[[i]])
  }else{
    # let the user know there were not domains identified in the canonical sequence initially
    canonical_domains_init <- "no"
    # add column to df_canonical_initially that will have a value of "no" for that specific Protein_name
    df_canonical_initially$Canonical_Domains_Initially[[i]] <- canonical_domains_init
    #print(df$Canonical_Domains_Initially[[i]])
    # use of the cat function to append the output text file when there are no domains identified in the canonical sequence
    cat("There were no domains identified in the canonical sequence by the SUPERFAMILY tool.",file= "domain_information_output.txt",append=TRUE, sep = "\n")
    
    
  }
  
  # Check for loss and gain of domains
  # check to see if the canonical domains are identical to the isoform domains
  # if they are, then there has been no loss/gain of domains
  if(identical(canonical_domains, isoform_domains) == TRUE){
    # add the following statement to the output text file when no domains have been gained or lost
    cat("No domains have been gained or lost in this novel isoform.",file= "domain_information_output.txt",append=TRUE, sep = "\n")
    # print the statement to the console if desired
    print("No domains have been gained or lost in this novel isoform.")
  }else{
    # check the sum of the frequency of the domains for the canonical versus that of the isoform 
    if(sum(df_canonical$Freq) > sum(df_isoform$Freq)){
      # add the information for loss/gain of domains to the output text file- this includes the number of each domain gained or lost
      cat(paste0("Domains lost: ", df_canonical$canonical_domains[which(df_canonical$Freq > df_isoform$Freq)], " ", df_canonical$Freq[which(df_canonical$Freq > df_isoform$Freq)] - df_isoform$Freq[which(df_canonical$Freq > df_isoform$Freq)]),file= "domain_information_output.txt",append=TRUE, sep = "\n")
      cat(paste0("Domains gained: ", df_isoform$isoform_domains[which(df_canonical$Freq < df_isoform$Freq)], " ", df_isoform$Freq[which(df_canonical$Freq < df_isoform$Freq)] - df_canonical$Freq[which(df_canonical$Freq < df_isoform$Freq)]),file= "domain_information_output.txt",append=TRUE, sep = "\n")
      
      # print the information to the console if desired
      print(paste0("Domains lost: ", df_canonical$canonical_domains[which(df_canonical$Freq > df_isoform$Freq)], " ", df_canonical$Freq[which(df_canonical$Freq > df_isoform$Freq)] - df_isoform$Freq[which(df_canonical$Freq > df_isoform$Freq)]))
      print(paste0("Domains gained: ", df_isoform$isoform_domains[which(df_canonical$Freq < df_isoform$Freq)], " ", df_isoform$Freq[which(df_canonical$Freq < df_isoform$Freq)] - df_canonical$Freq[which(df_canonical$Freq < df_isoform$Freq)]))
      # check the sum of the frequency of the domains for the canonical versus that of the isoform 
    }else if(sum(df_canonical$Freq) < sum(df_isoform$Freq)){
      # add the information for loss/gain of domains to the output text file- this includes the number of each domain gained or lost
      cat(paste0("Domains lost: ", df_canonical$canonical_domains[which(df_canonical$Freq > df_isoform$Freq)]," ", df_canonical$Freq[which(df_canonical$Freq > df_isoform$Freq)] - df_isoform$Freq[which(df_canonical$Freq > df_isoform$Freq)]),file= "domain_information_output.txt",append=TRUE, sep = "\n")
      cat(paste0("Domains gained: ", df_isoform$isoform_domains[which(df_canonical$Freq < df_isoform$Freq)], " ", df_isoform$Freq[which(df_canonical$Freq < df_isoform$Freq)] - df_canonical$Freq[which(df_canonical$Freq < df_isoform$Freq)]),file= "domain_information_output.txt",append=TRUE, sep = "\n")
      
      # print the information to the console if desired
      print(paste0("Domains lost: ", df_canonical$canonical_domains[which(df_canonical$Freq > df_isoform$Freq)]," ", df_canonical$Freq[which(df_canonical$Freq > df_isoform$Freq)] - df_isoform$Freq[which(df_canonical$Freq > df_isoform$Freq)]))
      print(paste0("Domains gained: ", df_isoform$isoform_domains[which(df_canonical$Freq < df_isoform$Freq)], " ", df_isoform$Freq[which(df_canonical$Freq < df_isoform$Freq)] - df_canonical$Freq[which(df_canonical$Freq < df_isoform$Freq)]))
    }else{
      # add the information for loss/gain of domains to the output text file- this includes the number of each domain gained or lost
      cat(paste0("Domains lost: ", df_canonical$canonical_domains[which(df_canonical$Freq > df_isoform$Freq)], " ", df_canonical$Freq[which(df_canonical$Freq > df_isoform$Freq)] - df_isoform$Freq[which(df_canonical$Freq > df_isoform$Freq)]),file= "domain_information_output.txt",append=TRUE, sep = "\n")
      cat(paste0("Domains gained: ", df_isoform$isoform_domains[which(df_canonical$Freq < df_isoform$Freq)], " ", df_isoform$Freq[which(df_canonical$Freq < df_isoform$Freq)] - df_canonical$Freq[which(df_canonical$Freq < df_isoform$Freq)]),file= "domain_information_output.txt",append=TRUE, sep = "\n")
      
      # print to the information to the console if desired
      print(paste0("Domains lost: ", df_canonical$canonical_domains[which(df_canonical$Freq > df_isoform$Freq)], " ", df_canonical$Freq[which(df_canonical$Freq > df_isoform$Freq)] - df_isoform$Freq[which(df_canonical$Freq > df_isoform$Freq)]))
      print(paste0("Domains gained: ", df_isoform$isoform_domains[which(df_canonical$Freq < df_isoform$Freq)], " ", df_isoform$Freq[which(df_canonical$Freq < df_isoform$Freq)] - df_canonical$Freq[which(df_canonical$Freq < df_isoform$Freq)]))
    }
  }
  
  
  # iterate i by one each time through the loop in order to look at the next protein file for the loss and gain of domains
  i <- i + 1
}

# write a csv file to store the dataframe that was generated to easily tell the user which sequences had domains identified for the canonical protein sequences.  # iterate i by one each time through the loop in order to generate the file of domain information for the next unique Seq_ID (i.e. UniProt ID)
write.csv(df_canonical_initially, "df_canonical_initially.csv")

